### ISSUE TITLE
Version 0.9.0

### ISSUE THREAD

**Issue by williamcanin** [snakypy/zshpower#4]
:sparkles: New feature!

**ZSHPower** now has the option to decolor your shell, a feature especially for those who like something unobtrusive.

Go to the configuration file and disable the option:

```toml
[general]
color.enable = false
```

[Version 0.9.0](https://github.com/snakypy/zshpower/tree/v0.9.0)
